sudo: required
services:
  - docker

before_install:
  - docker build -t pakkocool/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pakkocool/react-test npm test -- --coverage

after_success:
  - docker build -t pakkocool/multi-client ./client
  - docker build -t pakkocool/multi-nginx ./nginx
  - docker build -t pakkocool/multi-server ./server
  - docker build -t pakkocoool/multi-worker ./worker
  # Login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push them to DockerHub
  - docker push pakkocool/multi-client
  - docker push pakkocool/multi-nginx
  - docker push pakkocool/multi-server
  - docker push pakkocool/multi-worker